// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Converts natural language queries into Relational Algebra (RA) or SQL.
 *
 * - naturalLanguageToRaSql - A function that converts natural language to RA or SQL.
 * - NaturalLanguageToRaSqlInput - The input type for the naturalLanguageToRaSql function.
 * - NaturalLanguageToRaSqlOutput - The return type for the naturalLanguageToRaSql function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const NaturalLanguageToRaSqlInputSchema = z.object({
  naturalLanguageQuery: z
    .string()
    .describe('The natural language query to convert to RA or SQL.'),
});
export type NaturalLanguageToRaSqlInput = z.infer<typeof NaturalLanguageToRaSqlInputSchema>;

const NaturalLanguageToRaSqlOutputSchema = z.object({
  translatedQuery: z
    .string()
    .describe('The translated query in Relational Algebra or SQL.'),
});
export type NaturalLanguageToRaSqlOutput = z.infer<typeof NaturalLanguageToRaSqlOutputSchema>;

export async function naturalLanguageToRaSql(input: NaturalLanguageToRaSqlInput): Promise<NaturalLanguageToRaSqlOutput> {
  return naturalLanguageToRaSqlFlow(input);
}

const prompt = ai.definePrompt({
  name: 'naturalLanguageToRaSqlPrompt',
  input: {schema: NaturalLanguageToRaSqlInputSchema},
  output: {schema: NaturalLanguageToRaSqlOutputSchema},
  prompt: `You are an expert in translating natural language queries into Relational Algebra (RA) or SQL.

  Given the following natural language query, translate it into either Relational Algebra or SQL. Choose the most appropriate language based on the query.

  Natural Language Query: {{{naturalLanguageQuery}}}

  Translation:`,
});

const naturalLanguageToRaSqlFlow = ai.defineFlow(
  {
    name: 'naturalLanguageToRaSqlFlow',
    inputSchema: NaturalLanguageToRaSqlInputSchema,
    outputSchema: NaturalLanguageToRaSqlOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
